### ISSUE TITLE
Hi, I have some questions regarding this project

### ISSUE THREAD

**Issue by Joe23232** [francescop/ghono-xmr-randomx#1]
Hi, I have some questions regarding this project:

1. Am I able to import it as a library/crate into my own Rust code and integrate it into my own software so I can compile all into a single executable?
2. Does it support either [Beam](https://beam.mw/),  [Zcash](https://z.cash/) or [Monera](https://www.getmonero.org/) or any other privacy respecting cryptocurrency?
3. How efficient is it compared to something like [gminer](https://github.com/develsoftware/GMinerRelease)?
4. Do you guys get a commission from my cryptomining if I were to use this library/crate?
5. How well maintained is this project? How many people are working on it?

**Comment by francescop** [comment]
1 - the project is a binary, you are free to extract the parts you are interested into a library
2 - only monero
3 - never benchmarked it, i did this for fun. there are still parts i'd like to improve. keep in mind that the library that does the magic is a c library that is used by xmrig if i remember correctly. if you want to improve performances, that's where i'd look at
4 - no, but feel free to donate :stuck_out_tongue: 
5 - not very well, i did this for learning purposes and for fun and there's nothing that keeps me on this at this moment - apart from wanting to try out few things to improve performances

**Comment by Joe23232** [comment]
@francescop 

Interesting mate :) Is there a source code available for this?

Yes I would like to donate if I earn't enough :)

**Comment by francescop** [comment]
here it is: https://github.com/tevador/RandomX

**Comment by Joe23232** [comment]
Thanks mate :)
